"use server";

import { auth } from "@clerk/nextjs/server";
import { prisma } from "@/lib/prisma";

export async function downloadSummary(summaryId: string) {
  try {
    const { userId } = await auth();

    if (!userId) {
      return {
        success: false,
        error: "User not authenticated",
      };
    }

    // Get the summary from database
    const summary = await prisma.pDFSummaries.findFirst({
      where: {
        id: summaryId,
        userId: userId,
      },
    });

    if (!summary) {
      return {
        success: false,
        error: "Summary not found",
      };
    }

    // Create downloadable content with better formatting
    const content = `# ${summary.title}

**Source File:** ${summary.file_name}
**Created:** ${summary.created_at.toLocaleDateString("en-US", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
    })}
**Generated by:** SnapRead AI

================================================================================

${summary.summary_text}

================================================================================

*This summary was generated by SnapRead AI - Your intelligent PDF summarization tool.*
*Visit us at: https://snapread.ai*
`;

    return {
      success: true,
      data: {
        content,
        filename: `${summary.title
          .replace(/[^a-z0-9\s]/gi, "")
          .replace(/\s+/g, "_")
          .toLowerCase()}_summary.txt`,
        title: summary.title,
      },
    };
  } catch (error) {
    console.error("Error preparing download:", error);
    return {
      success: false,
      error: "Failed to prepare download",
    };
  }
}
